### ISSUE TITLE
SOLVED - Add a number in output name for don't overwrite the previous image after generate again

### ISSUE THREAD

**Issue by FutonGama** [rauldlnx10/sd-webui-swap-mukham#1]
Add a number in output name for don't overwrite the previous image after generate again

I loved the extension, works perfect, very good work.

**Comment by rauldlnx10** [comment]
Try updating now :)

**Comment by rauldlnx10** [comment]
> Add a number in output name for don't overwrite the previous image after generate again
> 
> I loved the extension, works perfect, very good work.

Im not a programmer but i think its fixed now, try updating.

**Comment by FutonGama** [comment]
Worked!!, very good :) . I have found another problem, video is not working here for some reason, here is a error. 
![image](https://github.com/rauldlnx10/sd-webui-swap-mukham/assets/95169493/535e04cd-6af0-4fd0-a630-57e12a1fb8ab)

**Comment by rauldlnx10** [comment]
Can you update and try now?

**Comment by FutonGama** [comment]
Yes, let me see

**Comment by rauldlnx10** [comment]
btw there will be more bugs, its an adapted extension so it will have all original app bugs.

**Comment by FutonGama** [comment]
Worked perfectly :)

I have received a error but the video have been created very fine.
Here the error just in case:

Traceback (most recent call last):
  File "C:\Programas\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Programas\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\Programas\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\Programas\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 336, in async_iteration
    return await iterator.__anext__()
  File "C:\Programas\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 329, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\Programas\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Programas\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Programas\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Programas\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 312, in run_sync_iterator_async
    return next(iterator)
  File "C:\Programas\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-swap-mukham\scripts\app.py", line 345, in process
    merge_img_sequence_from_ref(video_path, image_sequence, output_video_path)
  File "C:\Programas\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-swap-mukham\utils.py", line 186, in merge_img_sequence_from_ref
    edited_video_clip.close()
AttributeError: 'ImageSequenceClip' object has no attribute 'close'

**Comment by FutonGama** [comment]
> 
Even so, everything is going very well. You fixed the problems quickly even though you are not a programmer, congratulations. In advance, I know people are going to ask, so I'd rather ask before once, if you could take a look at some way to keep the options saved, that would be wonderful, so we don't have to keep changing the output directory every time, for example. 

Thanks for make the extension i loved!

**Comment by rauldlnx10** [comment]
> > 
> 
> Even so, everything is going very well. You fixed the problems quickly even though you are not a programmer, congratulations. In advance, I know people are going to ask, so I'd rather ask before once, if you could take a look at some way to keep the options saved, that would be wonderful, so we don't have to keep changing the output directory every time, for example.
> 
> Thanks for make the extension i loved!

I think the last error was fixed now, ill try to fix settings.

**Comment by FutonGama** [comment]
Its still giving the error here, the only thing what is happening with the error its just not showing the output inside the webui. 

It would also be interesting to have an option to automatically exclude the keyframes folder that is created after making a video so as not to accumulate things. But it would be nice to be able to check and uncheck the option because keyframes can be useful for other things for some people. So that you don't feel overwhelmed you can leave it for the future.

**Comment by rauldlnx10** [comment]
In the Output section you have a check to keep output sequence.

**Comment by FutonGama** [comment]
Oh so this option was for that, I had not understood and had forgotten to ask. All good :).

**Comment by rauldlnx10** [comment]
You can update, for now its not perfect but you can change folder permanently.
once you update you must edit settings.txt and add a folder like c:/outputs/swap, then in the app every time you change the output folder will write the settings.txt file with the new path, dont worry if every launch appears the default folder, it will use the settings.txt one.

**Comment by FutonGama** [comment]
On the new version is not working here, its saying the output directory do not exist. Is alright to keep the default output even without saving, i think people will like more like this, at least we can choose the folder output. Also i realized something, the videos are not working the audio, its generating muted.

**Comment by rauldlnx10** [comment]
> On the new version is not working here, its saying the output directory do not exist. Is alright to keep the default output even without saving, i think people will like more like this, at least we can choose the folder output. Also i realized something, the videos are not working the audio, its generating muted.

Im without a Pc for a few days, ill check It when i receive the new one.

**Comment by FutonGama** [comment]
> Im without a Pc for a few days, ill check It when i receive the new one.

Alright, i liked your extensions, if you want to keep in contact my discord is SrFuton#2443, i can test the things when you need. :)

**Comment by rauldlnx10** [comment]
> > Im without a Pc for a few days, ill check It when i receive the new one.
> 
> Alright, i liked your extensions, if you want to keep in contact my discord is SrFuton#2443, i can test the things when you need. :)

I have a question... Im going to add an integrated Gallery but i have 2 options:
a Stable Diffsion outputs gallery: You can drag images to the fields to swap
or
a Swap Folder Output Gallery?
