### ISSUE TITLE
SOLVED - TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by FxyDreamer** [rauldlnx10/sd-webui-swap-mukham#2]
I'm using google colab and this error started to appear. I tried it yesterday and it worked perfectly, both image and video, do you know how I could solve it?

<img width="1043" alt="asd" src="https://github.com/rauldlnx10/sd-webui-swap-mukham/assets/139799577/b4cf1504-60d0-48be-9fd3-bb09e5c649f1">

**Comment by rauldlnx10** [comment]
> I'm using google colab and this error started to appear. I tried it yesterday and it worked perfectly, both image and video, do you know how I could solve it?
> 
> <img alt="asd" width="1043" src="https://user-images.githubusercontent.com/139799577/256531042-b4cf1504-60d0-48be-9fd3-bb09e5c649f1.png">

The Colab versión is from the original app check swap mukham github

**Comment by FxyDreamer** [comment]
Yes, I tried that version both online and in automatic1111 but it has an nsfw filter (basically it doesn't allow you to do anything, even if it's not something nsfw). This version didn't have the filter two days ago and it worked perfectly in google colab, I'll try it locally see if it works, anyway thanks a lot!

**Comment by rauldlnx10** [comment]
> Yes, I tried that version both online and in automatic1111 but it has an nsfw filter (basically it doesn't allow you to do anything, even if it's not something nsfw). This version didn't have the filter two days ago and it worked perfectly in google colab, I'll try it locally see if it works, anyway thanks a lot!
I cant do nothing now, maybe the monday.

**Comment by FxyDreamer** [comment]
Thanks a lot!

**Comment by rauldlnx10** [comment]
> Thanks a lot!

If you can try it now, let me know it it works...
