### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by CherepanovAV** [rauldlnx10/sd-webui-swap-mukham#3]
Hello.
I am using a standalone ubuntu 22.04.
While working with the plugin I found a few problems, which can be easily fixed by modifying the Readme :)

The first problem occurred while installing the plugin.
The plugin installation failed because the "insightface" package was not installed

When installing this package manually, it turned out that the problem was the lack of developer packages, 
    python3.10-dev build-essential libssl-dev libffi-dev libxml2-dev libxslt1-dev 

I installed them using the following command
`> sudo apt install python3.10-dev build-essential libssl-dev libffi-dev libxml2-dev libxslt1-dev`.

I think it makes sense to specify this in the Requirements section of the Readme
The standard stable diffusion webui does not require them for installation.

The next problem is that the model is not loaded when loading models
inswapper_128.onnx

I had to look for the reason in the log and then install the model manually by downloading it from here - https://huggingface.co/deepinsight/inswapper/tree/main.

It is also desirable to reflect this in the readme

Also in the readme you should specify that before using the plugin you should specify an existing output directory in its settings.
When generating an image, the plugin does not create this directory by itself, which leads to an error.

After fixing these problems, the plugin worked. But I spent a couple of hours to fix them. If you fix the installation instructions, it will make it easier for others to install it

**Comment by rauldlnx10** [comment]
You must use the button Download Models to download all needed, models, i think i have fixed folder creation... the requirements install is giving me problems for now...

Ill update today, i added a button to delete the last generated image, im working o do it with videos too.

I know the basics but im not a programmer, so i use Chat Gpt a lot... Sorry i do my best.
