### ISSUE TITLE
SOLVED - Last update issue on Google Colab

### ISSUE THREAD

**Issue by FxyDreamer** [rauldlnx10/sd-webui-swap-mukham#5]
The update to the latest version shows me this error in google colab, it downloads everything perfectly but once opened the Swap tab is not shown, I tried it without any extension and it shows the same thing, I don't understand much about this but how could I install any old version if possible? The last version that worked without problems for me in colab was the one from 2 aug.

![issue](https://github.com/rauldlnx10/sd-webui-swap-mukham/assets/139799577/58a0ef93-637f-4d95-8cb8-97d4a7e1c91a)

**Comment by rauldlnx10** [comment]
In google Colab only works with: https://github.com/harisreedhar/Swap-Mukham

**Comment by FxyDreamer** [comment]
> Colab only works with: https://github.com/harisreedhar/Swap-Mukham, sorry

Too bad, it was working perfectly with this extension by installing it in google colab, I'll look for another option that doesn't have the nsfw filter, thank you very much anyway and sorry for the inconvenience!

**Comment by rauldlnx10** [comment]
> > Colab only works with: https://github.com/harisreedhar/Swap-Mukham, sorry
> 
> Too bad, it was working perfectly with this extension by installing it in google colab, I'll look for another option that doesn't have the nsfw filter, thank you very much anyway and sorry for the inconvenience!

I made some changes today, try and let me know.

**Comment by FxyDreamer** [comment]
Yep, I consulted the creator of the google colab that I was using and he told me about the "outputs" folder with the lowercase "o", generating the "Outputs" folder worked correctly, I just tried installing the extension from the colab and it works perfectly without the need to do this, thank you very much!

**Comment by rauldlnx10** [comment]
Perfect :)
