### ISSUE TITLE
Incompatibility with other popular extensions

### ISSUE THREAD

**Issue by nachodha** [rauldlnx10/sd-webui-swap-mukham#6]
Its not a bug but i think the report could be useful. Actually this extension is not compatible with roop, nor reactor (roop uncensored) because after last commit it uninstall onnxruntime and install  onnxruntime-gpu , causing a conflict between extensions.

**Comment by rauldlnx10** [comment]
found a solution, install mine 1st, then download roop but doing "git clone https://github.com/s0md3v/sd-webui-roop.git" in your extensions folder, then enter in sd-webui-roop folder and delete install.py, it will use onnxruntime-gpu without conflicts.

if you already installed both and you get errors:
Go to your venv/Scripts folder, open CMD and writte:

Activate
pip uninstall onnx onnxruntime onnxruntime-gpu
pip install onnx==1.14.0 onnxruntime-gpu==1.15.0

**Comment by nachodha** [comment]
> found a solution, install mine 1st, then download roop but doing "git clone https://github.com/s0md3v/sd-webui-roop.git" in your extensions folder, then enter in sd-webui-roop folder and delete install.py, it will use onnxruntime-gpu without conflicts.
> 
> if you already installed both and you get errors: Go to your venv/Scripts folder, open CMD and writte:
> 
> Activate pip uninstall onnx onnxruntime onnxruntime-gpu pip install onnx==1.14.0 onnxruntime-gpu==1.15.0

Solved this way (reinstalling onnx in the specified order). Thank you.
